@startuml
left to right direction

actor Biologieexperte as biologieExperte
actor BDW as bdw

rectangle "Datenintegrationssoftware" {
    (#001 CSV-Datei importieren) as (UC1)
    (#002 Neue Spalte hinzufügen) as (UC2)
    (#003 Zelleninhalt editieren) as (UC3)
    (#004 Abbildung erstellen) as (UC4)
    (#005 Automapper ausführen) as (UC5)
    (#006 Abgebildete Daten integrieren/importieren) as (UC6)
    (#007 Biodiversitätsfunddaten importieren) as (UC7)
    (#008 Aussagekräftige Fehlermeldungen\nrückmelden) as (UC8)
}


biologieExperte -- UC1
biologieExperte -- UC2
biologieExperte -- UC3
biologieExperte -- UC4
biologieExperte -- UC5
biologieExperte -- UC6

UC7 --- bdw
UC8 --- bdw

UC2 ..> UC1: <<extend>>
UC3 ..> UC1: <<extend>>

UC5 ..> UC4: <<include>>

UC6 .> UC7: <<include>>
UC8 .> UC7: <<extend>>
UC8 .> UC6: <<extend>>

'UC1 -[hidden]- UC3
'UC2 -[hidden]- UC4

@enduml