@startuml
left to right direction

actor Benutzer as Actor1

rectangle "Hosts/Datenbanken" {
    (#024 Host/Datenbank erstellen) as (UC24)
    (#025 Host/Datenbank editieren) as (UC25)
    (#026 Host/Datenbank löschen) as (UC26)
    (#027 Hosts/Datenbanken anzeigen) as (UC27)
    (#028 Host/Datenbank auswählen) as (UC28)
    (#029 Daten vom\nausgewählten Host laden) as (UC29)
}

note "Entweder vom ausgewählten Host\noder von der eigenen Datenbank" as N1

Actor1 -- (UC24)
Actor1 -- (UC25)
Actor1 -- (UC26)
Actor1 - (UC27)
Actor1 -- (UC28)

(UC28) ..> (UC29): <<include>>

N1 . (UC29)

(UC24) -[hidden]- (UC25)
(UC26) -[hidden]- (UC27)

@enduml