@startuml
left to right direction

actor Benutzer as Actor1

rectangle "Importierte Items" {
    (#019 Importierte Items anzeigen) as (UC19)
    (#020 Importierte Items filtern) as (UC20)
    (#021 Importierte Items\neinzeln editieren) as (UC21)
    (#022 Importierte Items\nin Masse editieren) as (UC22)
    (#023 Editierte importierte Items\nzum Ursprung zurücksetzen) as (UC23)
}

Actor1 -- (UC19)
Actor1 -- (UC20)
Actor1 -- (UC21)
Actor1 - (UC22)
Actor1 -- (UC23)

(UC20) .> (UC19) : <<extend>>

(UC19) -[hidden]- (UC22)
(UC20) -[hidden]- (UC23)

@enduml