@startuml
left to right direction

actor Benutzer as Actor1
actor Scheduler as Actor2

rectangle Mappings {
    (#030 Mapping erstellen) as (UC30)
    (#031 Mapping editieren) as (UC31)
    (#032 Mapping zur\nLöschung markieren) as (UC32)
    (#033 Mapping wiederherstellen) as (UC33)
    (#034 Mapping löschen) as (UC34)
    (#035 Mapping anzeigen) as (UC35)
    (#036 Mapping speichern) as (UC36)
    (#037 Gespeichertes Mapping laden) as (UC37)
    (#038 Gespeichertes Mapping löschen) as (UC38)
    (#039 Erstelltes Mapping zu\nimportierten Items zuweisen) as (UC39)
    (#040 Automapper konfigurieren) as (UC40)
    (#041 Konfigurierten\nAutomapper anwenden) as (UC41)
}

note "Host/Datenbank wird\nmit ausgewählt" as N1

Actor2 -- (UC34)

Actor1 -- (UC30)
Actor1 -- (UC31)
Actor1 -- (UC32)
Actor1 -- (UC33)
Actor1 -- (UC35)
Actor1 -- (UC36)
Actor1 -- (UC37)
Actor1 -- (UC38)
Actor1 -- (UC39)
Actor1 -- (UC40)
Actor1 -- (UC41)

N1 .. (UC30)
N1 .. (UC31)

(UC34) ..> (UC32) : <<extend>>
(UC33) ..> (UC32) : <<extend>>
(UC40) ..> (UC41) : <<extend>>

@enduml