@startuml
left to right direction

actor Benutzer as Actor1
actor Scheduler as Actor2

rectangle Projekte {
    (#001 Projekt erstellen) as (UC1)
    (#002 Projekt öffnen) as (UC2)
    (#003 Projekte anzeigen) as (UC3)
    (#004 Projekte filtern) as (UC4)
    (#005 Projekt editieren) as (UC5)
    (#006 Projekt zur Löschung markieren) as (UC6)
    (#007 Projekt wiederherstellen) as (UC7)
    (#008 Projekt löschen) as (UC8)
}

Actor2 -- (UC8)

Actor1 -- (UC1)
Actor1 -- (UC2)
Actor1 -- (UC3)
Actor1 -- (UC4)
Actor1 -- (UC5)
Actor1 -- (UC6)
Actor1 -- (UC7)

(UC4) ..> (UC3) : <<extend>>
(UC7) ..> UC6 : <<extend>>
(UC8) ..> UC6 : <<extend>>

@enduml