@startuml

rectangle Biodiversitätsfunddatensätze as biodiversitätsfunddatensätze

usecase Datenintegrationssoftware as datenIntegration
rectangle "Datenbank\n(Datenintegration)" as datenIntegrationDatenbank
rectangle "MinIO (S3-Objektspeicher)" as s3

rectangle "Biodiversity Warehouse (BDW)" as bdw
rectangle "Datenbank\n(BDW)" as bdwDatenbank

biodiversitätsfunddatensätze --> datenIntegration: direkter\nimport

datenIntegration -> datenIntegrationDatenbank: schreiben/lesen
biodiversitätsfunddatensätze --> s3: hochladen
s3 --> datenIntegration: importieren
datenIntegration --> bdw: integration/import der\nBiodiversitätsfunddatensätze

bdw -> bdwDatenbank: schreiben/lesen

@enduml