@startuml
start
group Batch Post-Processing
    group Batch Pre-Processing
        :Call batch pre-processing;
    end group
    group Batch Processing
        :Call batch processing;
    end group
    if (last batch is not empty AND failed=false?) is (yes) then
        group Async Batch Processing
            :Call async batch processing;
        end group
    else (no)
    endif
    while (is activeBatchesScope greater than 0?)
        :Wait for remaining batches to finish (sleep);
    endwhile
    if (failed=false AND is activeBatchesScope <= 0?) is (yes) then
        :Set scope finish flag to true;
    else (no)
    endif
end group
stop
@enduml
