@startuml
start
group Import from File
    :Check if user has permission to import a file to project;
    :Create csv reader from byte array;
    :Count number of lines in file;
    group Async multi-threaded Import
      :Call async multi-threaded Import;
    end group
end group
stop
@enduml
