@startuml
start
group Batch Processing
    group Batch Pre-Processing
        :Call batch pre-processing;
    end group
    while (failed=false AND file to import has next line)
        if (scope is marked for deletion OR scope is manually interrupted?) is (yes) then
            :Set failed=true;
        else (no)
            :Set failed=false;
        endif
        :Set batchIndex based on current line and batchSize configuration;
        if (is batch already processed (checkpointing)?) is (yes) then
        else (no)
            :Transform current line into item entity;
            :Add item entity to batch;
            if (is batch full?) is (yes) then
                group Async Batch Processing
                    :Call async batch processing;
                end group
                :Clear batch;
            else (no)
            endif
        endif
    endwhile
    group Batch Post-Processing
        :Call batch post-processing;
    end group
end group
stop
@enduml
