@startuml
hide empty description

[*] --> MAPPED
MAPPED -> INTEGRATED: Integration\nerfolgreich
MAPPED -> FAILED: Integration\nfehlgeschlagen
FAILED -> FAILED: Integration\nfehlgeschlagen
FAILED --> INTEGRATED
INTEGRATED --> [*]

@enduml