@startuml
left to right direction

package "org.dataintegration.model" as modelPackage {

    node config {
        class BatchConfigModel {
            - batchSize: int
            - batchRetryScopeMax: int
            - batchRetryBatchMax: int
        }

        class BatchWaitingConfigModel {
            - batchRetryScopeDelayMs: long
            - batchRetryBatchDelayMs: long
            - batchWaitForFullQueueDelayMs: long
            - batchWaitForBatchesToFinishDelayMs: long
        }

        class AsyncBatchConfigModel {
            - executorService: ExecutorService
            - activeBatches: AtomicLong
            - batchThreads: int
        }
    }

    class BatchProcessingModel {
        - projectId: UUID
        - scopeId: UUID
        - scopeKey: String
        - batchIndex: long
        - batchSize: int
        - batch: List<ItemEntity>
    }


}

@enduml