@startuml

autonumber

actor Datenintegrationssoftware <<System>>

participant "BDW Backend" as backend
participant "Funddatenimport" as import

database "Atlas Datenbank\n(fish,mammal,...)" as datenbank

Datenintegrationssoftware -> backend: REST POST /records/import/{atlas}\nBODY: Abgebildete Daten

activate backend
backend -> import: Abgebildete Daten

activate import
import -> import: Validierung\nTransformationen

import -> datenbank: Lesen
datenbank --> import: Daten zur weiteren Validierung

import -> datenbank: Persistieren
datenbank --> import

import -> import: Funddatenimportergebnisse sammeln

import --> backend: Funddatenimportergebnisse
backend --> Datenintegrationssoftware: Funddatenimportergebnisse

@enduml